image: ubuntu

stages:
  - build
  - test

build-test:
  stage: build
  before_script:
    - apt-get update --yes
    - apt-get install --yes cmake gcc g++ ninja-build
  script:
    - mkdir build
    - cd build
    - cmake .. -G Ninja
    - ninja
